services:
  postgres:
    image: postgres:16
    container_name: versia_db
    environment:
      POSTGRES_DB: versia_db
      POSTGRES_USER: versia_user
      POSTGRES_PASSWORD: versia123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
