# Generated by Django 6.0.3 on 2026-04-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='cursos.aula')),
            ],
            options={
                'verbose_name': 'Progresso da Aula',
                'verbose_name_plural': 'Progressos das Aulas',
            },
        ),
    ]
